version: "3.9"

services:
  backend:
    container_name: "backend"
    image: mindlessdoc/yd-backend:latest
    ports:
      - "3000:3000"

  client:
    container_name: "client"
    image: ranatasha/yd-client:latest
    ports:
      - "3001:3000"

  admin:
    container_name: "admin"
    image: siailyadev/yd-admin:0.0.1
    ports:
      - "3002:80"
