version: "3.9"

services:
  backend:
    container_name: "backend"
    image: philipoff/yd-backend:latest
    ports:
      - "3000:3000"

  client:
    container_name: "client"
    image: ranatasha/yd-client:latest
    ports:
      - "3001:3000"

  admin:
    container_name: "admin"
    image: siailyadev/yd-admin:0.0.1
    ports:
      - "3002:80"

  postgres:
    container_name: your_dormitory_db
    image: postgres:14.5
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d your_dormitory" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: "your_dormitory"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "1488"
      PGDATA: /var/lib/postgresql/data/some_name/
    volumes:
      - yd-database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  yd-database:
    external: true
