name: Your-Dormitory-Admin CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'admin/**'

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN_ADMIN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN_ADMIN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./admin/
          push: true
          tags: siailyadev/yd-admin:0.0.1

      - name: Invoke deployment Portainer hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{ "deploy": "true" }'
