name: Your-Dormitory-Client CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'client/**'

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN_CLIENT }}
          password: ${{ secrets.DOCKER_HUB_TOKEN_CLIENT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./client/
          push: true
          tags: ranatasha/yd-client:latest

      - name: Invoke deployment Portainer hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{ "deploy": "true" }'